package com.rabbitmq.demo.entity.business;

import java.io.Serializable;

public class BsFinanceLoanResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.e_note_no
     *
     * @mbggenerated
     */
    private String eNoteNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.p_e_note_no
     *
     * @mbggenerated
     */
    private String pENoteNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.loan_date
     *
     * @mbggenerated
     */
    private String loanDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.institution
     *
     * @mbggenerated
     */
    private String institution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.batch_No
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.periods_num
     *
     * @mbggenerated
     */
    private String periodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.bank_account
     *
     * @mbggenerated
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_finance_loan_result.expire_date
     *
     * @mbggenerated
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_finance_loan_result
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.id
     *
     * @return the value of bs_finance_loan_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.id
     *
     * @param id the value for bs_finance_loan_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.e_note_no
     *
     * @return the value of bs_finance_loan_result.e_note_no
     *
     * @mbggenerated
     */
    public String geteNoteNo() {
        return eNoteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.e_note_no
     *
     * @param eNoteNo the value for bs_finance_loan_result.e_note_no
     *
     * @mbggenerated
     */
    public void seteNoteNo(String eNoteNo) {
        this.eNoteNo = eNoteNo == null ? null : eNoteNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.p_e_note_no
     *
     * @return the value of bs_finance_loan_result.p_e_note_no
     *
     * @mbggenerated
     */
    public String getpENoteNo() {
        return pENoteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.p_e_note_no
     *
     * @param pENoteNo the value for bs_finance_loan_result.p_e_note_no
     *
     * @mbggenerated
     */
    public void setpENoteNo(String pENoteNo) {
        this.pENoteNo = pENoteNo == null ? null : pENoteNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.amount
     *
     * @return the value of bs_finance_loan_result.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.amount
     *
     * @param amount the value for bs_finance_loan_result.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.state
     *
     * @return the value of bs_finance_loan_result.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.state
     *
     * @param state the value for bs_finance_loan_result.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.loan_date
     *
     * @return the value of bs_finance_loan_result.loan_date
     *
     * @mbggenerated
     */
    public String getLoanDate() {
        return loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.loan_date
     *
     * @param loanDate the value for bs_finance_loan_result.loan_date
     *
     * @mbggenerated
     */
    public void setLoanDate(String loanDate) {
        this.loanDate = loanDate == null ? null : loanDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.institution
     *
     * @return the value of bs_finance_loan_result.institution
     *
     * @mbggenerated
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.institution
     *
     * @param institution the value for bs_finance_loan_result.institution
     *
     * @mbggenerated
     */
    public void setInstitution(String institution) {
        this.institution = institution == null ? null : institution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.uuid
     *
     * @return the value of bs_finance_loan_result.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.uuid
     *
     * @param uuid the value for bs_finance_loan_result.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.batch_No
     *
     * @return the value of bs_finance_loan_result.batch_No
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.batch_No
     *
     * @param batchNo the value for bs_finance_loan_result.batch_No
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.periods_num
     *
     * @return the value of bs_finance_loan_result.periods_num
     *
     * @mbggenerated
     */
    public String getPeriodsNum() {
        return periodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.periods_num
     *
     * @param periodsNum the value for bs_finance_loan_result.periods_num
     *
     * @mbggenerated
     */
    public void setPeriodsNum(String periodsNum) {
        this.periodsNum = periodsNum == null ? null : periodsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.company
     *
     * @return the value of bs_finance_loan_result.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.company
     *
     * @param company the value for bs_finance_loan_result.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.bank_name
     *
     * @return the value of bs_finance_loan_result.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.bank_name
     *
     * @param bankName the value for bs_finance_loan_result.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.bank_account
     *
     * @return the value of bs_finance_loan_result.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.bank_account
     *
     * @param bankAccount the value for bs_finance_loan_result.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_finance_loan_result.expire_date
     *
     * @return the value of bs_finance_loan_result.expire_date
     *
     * @mbggenerated
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_finance_loan_result.expire_date
     *
     * @param expireDate the value for bs_finance_loan_result.expire_date
     *
     * @mbggenerated
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate == null ? null : expireDate.trim();
    }
}